// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "ringover/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// TaskService is an autogenerated mock type for the TaskService type
type TaskService struct {
	mock.Mock
}

type TaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskService) EXPECT() *TaskService_Expecter {
	return &TaskService_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: ctx, input
func (_m *TaskService) CreateTask(ctx context.Context, input domain.CreateTaskInput) (domain.Task, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTaskInput) (domain.Task, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTaskInput) domain.Task); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateTaskInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type TaskService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.CreateTaskInput
func (_e *TaskService_Expecter) CreateTask(ctx interface{}, input interface{}) *TaskService_CreateTask_Call {
	return &TaskService_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, input)}
}

func (_c *TaskService_CreateTask_Call) Run(run func(ctx context.Context, input domain.CreateTaskInput)) *TaskService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CreateTaskInput))
	})
	return _c
}

func (_c *TaskService_CreateTask_Call) Return(_a0 domain.Task, _a1 error) *TaskService_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_CreateTask_Call) RunAndReturn(run func(context.Context, domain.CreateTaskInput) (domain.Task, error)) *TaskService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: ctx, taskID
func (_m *TaskService) DeleteTask(ctx context.Context, taskID uint64) error {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskService_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type TaskService_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uint64
func (_e *TaskService_Expecter) DeleteTask(ctx interface{}, taskID interface{}) *TaskService_DeleteTask_Call {
	return &TaskService_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, taskID)}
}

func (_c *TaskService_DeleteTask_Call) Run(run func(ctx context.Context, taskID uint64)) *TaskService_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *TaskService_DeleteTask_Call) Return(_a0 error) *TaskService_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskService_DeleteTask_Call) RunAndReturn(run func(context.Context, uint64) error) *TaskService_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListRootSubtasks provides a mock function with given fields: ctx, taskID
func (_m *TaskService) ListRootSubtasks(ctx context.Context, taskID uint64) ([]domain.Task, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListRootSubtasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]domain.Task, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []domain.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_ListRootSubtasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRootSubtasks'
type TaskService_ListRootSubtasks_Call struct {
	*mock.Call
}

// ListRootSubtasks is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uint64
func (_e *TaskService_Expecter) ListRootSubtasks(ctx interface{}, taskID interface{}) *TaskService_ListRootSubtasks_Call {
	return &TaskService_ListRootSubtasks_Call{Call: _e.mock.On("ListRootSubtasks", ctx, taskID)}
}

func (_c *TaskService_ListRootSubtasks_Call) Run(run func(ctx context.Context, taskID uint64)) *TaskService_ListRootSubtasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *TaskService_ListRootSubtasks_Call) Return(_a0 []domain.Task, _a1 error) *TaskService_ListRootSubtasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_ListRootSubtasks_Call) RunAndReturn(run func(context.Context, uint64) ([]domain.Task, error)) *TaskService_ListRootSubtasks_Call {
	_c.Call.Return(run)
	return _c
}

// ListRootTasks provides a mock function with given fields: ctx
func (_m *TaskService) ListRootTasks(ctx context.Context) ([]domain.Task, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRootTasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Task, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Task); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_ListRootTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRootTasks'
type TaskService_ListRootTasks_Call struct {
	*mock.Call
}

// ListRootTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TaskService_Expecter) ListRootTasks(ctx interface{}) *TaskService_ListRootTasks_Call {
	return &TaskService_ListRootTasks_Call{Call: _e.mock.On("ListRootTasks", ctx)}
}

func (_c *TaskService_ListRootTasks_Call) Run(run func(ctx context.Context)) *TaskService_ListRootTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TaskService_ListRootTasks_Call) Return(_a0 []domain.Task, _a1 error) *TaskService_ListRootTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_ListRootTasks_Call) RunAndReturn(run func(context.Context) ([]domain.Task, error)) *TaskService_ListRootTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: ctx, taskID, input
func (_m *TaskService) UpdateTask(ctx context.Context, taskID uint64, input domain.UpdateTaskInput) (domain.Task, error) {
	ret := _m.Called(ctx, taskID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, domain.UpdateTaskInput) (domain.Task, error)); ok {
		return rf(ctx, taskID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, domain.UpdateTaskInput) domain.Task); ok {
		r0 = rf(ctx, taskID, input)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, domain.UpdateTaskInput) error); ok {
		r1 = rf(ctx, taskID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskService_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type TaskService_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uint64
//   - input domain.UpdateTaskInput
func (_e *TaskService_Expecter) UpdateTask(ctx interface{}, taskID interface{}, input interface{}) *TaskService_UpdateTask_Call {
	return &TaskService_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, taskID, input)}
}

func (_c *TaskService_UpdateTask_Call) Run(run func(ctx context.Context, taskID uint64, input domain.UpdateTaskInput)) *TaskService_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(domain.UpdateTaskInput))
	})
	return _c
}

func (_c *TaskService_UpdateTask_Call) Return(_a0 domain.Task, _a1 error) *TaskService_UpdateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskService_UpdateTask_Call) RunAndReturn(run func(context.Context, uint64, domain.UpdateTaskInput) (domain.Task, error)) *TaskService_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskService creates a new instance of TaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskService {
	mock := &TaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
